import { DonationItem, MembershipPlan, NotificationItem, UserProfile } from '../types';

export const MOCK_USERS: Record<string, UserProfile> = {
  donor_1: {
    id: 'donor_1',
    name: 'Chef Rajesh Sharma',
    organization: 'Royal Orchid Banquet & Caterers',
    role: 'donor',
    address: 'Sector 18, Commercial Hub, New Delhi',
    coordinates: { lat: 28.5355, lng: 77.391 },
    phone: '+91 98112 34567',
    email: 'catering@royalorchid.in',
    rating: 4.9,
    verified: true,
    activeMembership: {
      planId: 'quarterly',
      planName: 'Quarterly Corporate Plan',
      startedAt: '2026-08-01',
      expiresAt: '2026-11-01',
      daysRemaining: 31,
      price: 3000,
    },
  },
  ngo_1: {
    id: 'ngo_1',
    name: 'Sister Mary & Team',
    organization: 'Asha Community Food Bank & Shelter',
    role: 'ngo',
    address: 'Mayur Vihar Phase 1, Community Center, New Delhi',
    coordinates: { lat: 28.6085, lng: 77.2965 },
    phone: '+91 98734 56789',
    email: 'relief@ashafoodbank.org',
    rating: 4.95,
    verified: true,
  },
  ngo_2: {
    id: 'ngo_2',
    name: 'Vikram Joshi',
    organization: 'Seva Samarpan Children Foundation',
    role: 'ngo',
    address: 'Lajpat Nagar IV, New Delhi',
    coordinates: { lat: 28.5672, lng: 77.2435 },
    phone: '+91 98210 98765',
    email: 'contact@sevasamarpan.org',
    rating: 4.88,
    verified: true,
  },
  delivery_1: {
    id: 'delivery_1',
    name: 'Amit Verma',
    organization: 'SLAstice Green Fleet Partner',
    role: 'delivery',
    address: 'Noida City Center Hub',
    coordinates: { lat: 28.5708, lng: 77.3562 },
    phone: '+91 99102 88471',
    email: 'amit.verma@slastice-courier.net',
    rating: 4.92,
    verified: true,
  },
  admin_1: {
    id: 'admin_1',
    name: 'Priyasha Sengupta',
    organization: 'SLAstice Central Oversight & Governance',
    role: 'admin',
    address: 'HQ Cyber City, Tower B, Gurugram',
    coordinates: { lat: 28.4952, lng: 77.0891 },
    phone: '+91 97171 00021',
    email: 'admin@slastice.org',
    rating: 5.0,
    verified: true,
  },
};

export const MEMBERSHIP_PLANS: MembershipPlan[] = [
  {
    id: 'monthly',
    name: 'Monthly Contributor',
    duration: '1 Month',
    price: 1000,
    periodMonths: 1,
    features: [
      'Priority nearby NGO smart matching (< 1.5 min)',
      'Digital 3-stage chain-of-custody audit exports',
      'Automated volunteer delivery dispatch routing',
      'Verified ESG Food Waste Abatement Badge',
      'Email & SMS alerts for expiring batches',
    ],
  },
  {
    id: 'quarterly',
    name: 'Quarterly Community Partner',
    duration: '3 Months',
    price: 3000,
    periodMonths: 3,
    popular: true,
    features: [
      'All Monthly Contributor perks included',
      'Free thermal insulation crate pack for transit',
      'Live temperature compliance digital logging',
      'Quarterly Tax-exempt 80G CSR Certificate',
      'Dedicated SLAstice Emergency Hotline Coordinator',
      'Custom NGO direct matching agreements',
    ],
  },
  {
    id: 'half_yearly',
    name: 'Half-Yearly ESG Enterprise',
    duration: '6 Months',
    price: 6000,
    periodMonths: 6,
    features: [
      'All Quarterly perks included',
      'Zero-wait guaranteed rapid delivery fleet allocation',
      'Full API webhook integration with POS & hotel ERP',
      'Quarterly executive food sustainability report',
      'Custom branded traceability public portal page',
      'Bulk pickup fleet for weddings and conventions (>200kg)',
    ],
  },
];

// High quality food photos as reliable web assets
export const SAMPLE_FOOD_IMAGES = {
  freshMeals: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=700&auto=format&fit=crop&q=80',
  steamingRice: 'https://images.unsplash.com/photo-1589302168068-964664d93dc0?w=700&auto=format&fit=crop&q=80',
  breadBakery: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=700&auto=format&fit=crop&q=80',
  freshVegetables: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=700&auto=format&fit=crop&q=80',
  buffetDishes: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=700&auto=format&fit=crop&q=80',
  packagedGoods: 'https://images.unsplash.com/photo-1584727638096-042c45049ebe?w=700&auto=format&fit=crop&q=80',
};

export const INITIAL_DONATIONS: DonationItem[] = [
  {
    id: 'SLA-DON-2026-00021',
    title: 'Warm Vegetable Biryani & Dal Makhani',
    category: 'Cooked Meals',
    quantity: 35,
    unit: 'kg',
    dietaryType: 'Veg',
    preparedAt: '2026-10-01 11:30 AM',
    expiryAt: '2026-10-01 07:30 PM',
    storageCondition: 'Hot Insulated (>60°C)',
    description: 'Surplus wedding luncheon preparation. Kept in sealed industrial food-grade stainless steel thermal containers since preparation.',
    allergens: 'Contains dairy (butter/cream in Dal), cashew nuts in garnish',
    donorId: 'donor_1',
    donorName: 'Chef Rajesh Sharma',
    donorOrg: 'Royal Orchid Banquet & Caterers',
    donorPhone: '+91 98112 34567',
    donorLocation: {
      address: 'Sector 18, Commercial Hub, New Delhi',
      lat: 28.5355,
      lng: 77.391,
    },
    foodImage: SAMPLE_FOOD_IMAGES.steamingRice,
    donorScreening: {
      screeningId: 'CNN-SCR-2026-1042',
      timestamp: '2026-10-01 12:15 PM',
      condition: 'Fresh',
      confidence: 0.96,
      detectedFood: 'Cooked Rice Pilaf / Biryani with Lentil Gravy',
      visualIndicators: [
        'Vigorous thermal steam condensation detected',
        'Rice grains intact with no clumping or oil rancidity sheen',
        'Stainless thermal cambro container properly clamped',
        'Vibrant natural spice coloration and uniform appearance',
      ],
      recommendedWindow: 'Safe for consumption within 5 hours at current insulation',
      advisoryNotes: 'AI visual screening passed with high confidence. Hygiene checklist approved.',
      stage: 'donor',
      inspectorName: 'Chef Rajesh Sharma',
      imageUrl: SAMPLE_FOOD_IMAGES.steamingRice,
      temperatureEstimate: '64.5°C',
      packagingIntegrity: 'Sealed Hot-Holding Containers',
    },
    status: 'IN_TRANSIT',
    createdAt: '2026-10-01 12:10 PM',
    requestedByNGO: {
      ngoId: 'ngo_1',
      ngoName: 'Asha Community Food Bank & Shelter',
      requestedAt: '2026-10-01 12:35 PM',
      beneficiariesTarget: 70,
      notes: 'Urgent need for evening community meal distribution for 70 shelter residents.',
      ngoLocation: {
        address: 'Mayur Vihar Phase 1, Community Center, New Delhi',
        lat: 28.6085,
        lng: 77.2965,
      },
    },
    assignedDeliveryPartner: {
      partnerId: 'delivery_1',
      partnerName: 'Amit Verma',
      partnerPhone: '+91 99102 88471',
      vehicleType: 'E-Bike',
      assignedAt: '2026-10-01 01:05 PM',
      pickupTime: '2026-10-01 01:25 PM',
      currentCoordinates: { lat: 28.572, lng: 77.344 },
      transitProgress: 65,
      pickupScreening: {
        screeningId: 'CNN-SCR-2026-1049',
        timestamp: '2026-10-01 01:26 PM',
        condition: 'Fresh',
        confidence: 0.94,
        detectedFood: 'Cooked Biryani Containers (Pickup Check)',
        visualIndicators: [
          'Containers inspected at donor handover',
          'Outer seals undamaged and clean',
          'Temperature test reads hot (>62°C)',
          'No spillage or foreign contamination during loading',
        ],
        recommendedWindow: 'Direct transit to Asha Food Bank',
        advisoryNotes: 'Stage 2 pickup verification validated by driver Amit Verma.',
        stage: 'pickup',
        inspectorName: 'Amit Verma (Delivery Partner)',
        imageUrl: SAMPLE_FOOD_IMAGES.steamingRice,
        temperatureEstimate: '63.0°C',
        packagingIntegrity: 'Strapped in Thermal Transit Bag',
      },
    },
    traceabilityLog: [
      {
        id: 'evt_1',
        timestamp: '2026-10-01 12:15 PM',
        stage: 'Donation Created & Stage 1 Visual Screening',
        status: 'AVAILABLE',
        actor: 'Chef Rajesh Sharma (Donor)',
        actorRole: 'donor',
        note: 'Listed 35 kg Vegetable Biryani. CNN screening verified "Fresh" (96% confidence).',
        location: 'Sector 18, Commercial Hub, New Delhi',
      },
      {
        id: 'evt_2',
        timestamp: '2026-10-01 12:35 PM',
        stage: 'NGO Claim Request',
        status: 'REQUESTED',
        actor: 'Sister Mary (Asha Community Food Bank)',
        actorRole: 'ngo',
        note: 'Requested food for 70 community kitchen beneficiaries.',
        location: 'Mayur Vihar Phase 1, New Delhi',
      },
      {
        id: 'evt_3',
        timestamp: '2026-10-01 12:45 PM',
        stage: 'Donor Approved Request',
        status: 'APPROVED',
        actor: 'Chef Rajesh Sharma (Donor)',
        actorRole: 'donor',
        note: 'Accepted request. Ready for delivery dispatch.',
        location: 'Sector 18, Commercial Hub, New Delhi',
      },
      {
        id: 'evt_4',
        timestamp: '2026-10-01 01:05 PM',
        stage: 'Delivery Partner Assigned',
        status: 'DELIVERY_PARTNER_ASSIGNED',
        actor: 'Amit Verma (Delivery Partner)',
        actorRole: 'delivery',
        note: 'Accepted delivery mission via E-Bike cargo.',
        location: 'Noida Hub to Sector 18',
      },
      {
        id: 'evt_5',
        timestamp: '2026-10-01 01:26 PM',
        stage: 'Stage 2 Pickup Camera Verification',
        status: 'COLLECTED',
        actor: 'Amit Verma (Delivery Partner)',
        actorRole: 'delivery',
        note: 'Arrived at kitchen. Captured verification photo. Condition verified "Fresh" (94%). Food loaded in thermal bag.',
        location: 'Sector 18, Commercial Hub, New Delhi',
      },
      {
        id: 'evt_6',
        timestamp: '2026-10-01 01:32 PM',
        stage: 'In Transit to Receiver',
        status: 'IN_TRANSIT',
        actor: 'Amit Verma (Delivery Partner)',
        actorRole: 'delivery',
        note: 'E-Bike on route to Mayur Vihar Phase 1. Live GPS tracking active.',
        location: 'En-route DND Flyway, 65% completed',
      },
    ],
  },
  {
    id: 'SLA-DON-2026-00022',
    title: 'Artisan Whole Wheat Bread & French Baguettes',
    category: 'Bakery & Bread',
    quantity: 45,
    unit: 'packs',
    dietaryType: 'Veg',
    preparedAt: '2026-10-01 06:00 AM',
    expiryAt: '2026-10-02 06:00 PM',
    storageCondition: 'Ambient Room Temp',
    description: 'Freshly baked surplus loaves from morning artisanal batch. Packaged in breathable brown paper sleeves.',
    allergens: 'Gluten (Wheat)',
    donorId: 'donor_2',
    donorName: 'Le Petit Boulanger Bakery',
    donorOrg: 'Connaught Place Bakery Collective',
    donorPhone: '+91 98101 22334',
    donorLocation: {
      address: 'Inner Circle, Connaught Place, New Delhi',
      lat: 28.6328,
      lng: 77.2197,
    },
    foodImage: SAMPLE_FOOD_IMAGES.breadBakery,
    donorScreening: {
      screeningId: 'CNN-SCR-2026-1033',
      timestamp: '2026-10-01 09:30 AM',
      condition: 'Fresh',
      confidence: 0.98,
      detectedFood: 'Artisan Sourdough and Baguettes',
      visualIndicators: [
        'Golden crust with even caramelized blister pattern',
        'No mold spores or excessive crust hardening',
        'Clean dry packaging with bakery batch seals intact',
      ],
      recommendedWindow: 'Consume within 36 hours for optimal softness',
      advisoryNotes: 'Excellent quality bakery surplus. Zero moisture spoilage.',
      stage: 'donor',
      inspectorName: 'Master Baker Jean-Luc',
      imageUrl: SAMPLE_FOOD_IMAGES.breadBakery,
      temperatureEstimate: '22.0°C (Ambient)',
      packagingIntegrity: 'Sealed Bakery Sleeves',
    },
    status: 'AVAILABLE',
    createdAt: '2026-10-01 09:40 AM',
    traceabilityLog: [
      {
        id: 'evt_bread_1',
        timestamp: '2026-10-01 09:40 AM',
        stage: 'Donation Created & Stage 1 Visual Screening',
        status: 'AVAILABLE',
        actor: 'Le Petit Boulanger Bakery (Donor)',
        actorRole: 'donor',
        note: 'Listed 45 packs of fresh artisan bread. AI screening confirmed "Fresh" (98% confidence).',
        location: 'Connaught Place, New Delhi',
      },
    ],
  },
  {
    id: 'SLA-DON-2026-00023',
    title: 'Assorted Steamed Rice & Dal Khichdi Meals',
    category: 'Cooked Meals',
    quantity: 50,
    unit: 'meals',
    dietaryType: 'Veg',
    preparedAt: '2026-10-01 10:00 AM',
    expiryAt: '2026-10-01 05:00 PM',
    storageCondition: 'Hot Insulated (>60°C)',
    description: 'Corporate cafeteria surplus cooked in hygienic steam kettles. Packed in individual biodegradable meal boxes.',
    allergens: 'Lentils, Cumin',
    donorId: 'donor_3',
    donorName: 'TechPark Cafeteria Services',
    donorOrg: 'DLF CyberCity Tech Dining',
    donorPhone: '+91 99990 11223',
    donorLocation: {
      address: 'DLF CyberCity Phase 2, Gurugram',
      lat: 28.4905,
      lng: 77.0898,
    },
    foodImage: SAMPLE_FOOD_IMAGES.freshMeals,
    donorScreening: {
      screeningId: 'CNN-SCR-2026-1011',
      timestamp: '2026-10-01 11:00 AM',
      condition: 'Moderately Fresh',
      confidence: 0.91,
      detectedFood: 'Hot Lentil & Rice Stew (Khichdi)',
      visualIndicators: [
        'Safe hot holding temperature maintained',
        'Consolidated meal boxes sealed with tamper-evident tape',
        'Minor steam cooling observed but safely within food standards',
      ],
      recommendedWindow: 'Redistribute within next 3.5 hours',
      advisoryNotes: 'Moderately fresh rating due to 4-hour remaining shelf-life threshold.',
      stage: 'donor',
      inspectorName: 'Cafeteria Manager Sunita Rao',
      imageUrl: SAMPLE_FOOD_IMAGES.freshMeals,
      temperatureEstimate: '59.8°C',
      packagingIntegrity: 'Biodegradable Meal Boxes',
    },
    status: 'REQUESTED',
    createdAt: '2026-10-01 11:10 AM',
    requestedByNGO: {
      ngoId: 'ngo_2',
      ngoName: 'Seva Samarpan Children Foundation',
      requestedAt: '2026-10-01 11:45 AM',
      beneficiariesTarget: 50,
      notes: 'Requesting 50 meals for children shelter lunch distribution.',
      ngoLocation: {
        address: 'Lajpat Nagar IV, New Delhi',
        lat: 28.5672,
        lng: 77.2435,
      },
    },
    traceabilityLog: [
      {
        id: 'evt_khi_1',
        timestamp: '2026-10-01 11:10 AM',
        stage: 'Donation Created & Stage 1 Visual Screening',
        status: 'AVAILABLE',
        actor: 'TechPark Cafeteria (Donor)',
        actorRole: 'donor',
        note: 'Listed 50 boxed meals with AI screening (Moderately Fresh, 91%).',
        location: 'DLF CyberCity, Gurugram',
      },
      {
        id: 'evt_khi_2',
        timestamp: '2026-10-01 11:45 AM',
        stage: 'NGO Request Submitted',
        status: 'REQUESTED',
        actor: 'Vikram Joshi (Seva Samarpan)',
        actorRole: 'ngo',
        note: 'Requested 50 meals for midday meal program.',
        location: 'Lajpat Nagar IV, New Delhi',
      },
    ],
  },
  {
    id: 'SLA-DON-2026-00020',
    title: 'Fresh Farm Hydroponic Lettuce & Bell Peppers',
    category: 'Fresh Produce',
    quantity: 28,
    unit: 'kg',
    dietaryType: 'Vegan',
    preparedAt: '2026-09-30 04:00 PM',
    expiryAt: '2026-10-03 08:00 PM',
    storageCondition: 'Refrigerated (<4°C)',
    description: 'Crisp green leaf and red/yellow bell peppers from clean hydroponic vertical farm batch.',
    donorId: 'donor_1',
    donorName: 'Chef Rajesh Sharma',
    donorOrg: 'Royal Orchid Banquet & Caterers',
    donorPhone: '+91 98112 34567',
    donorLocation: {
      address: 'Sector 18, Commercial Hub, New Delhi',
      lat: 28.5355,
      lng: 77.391,
    },
    foodImage: SAMPLE_FOOD_IMAGES.freshVegetables,
    donorScreening: {
      screeningId: 'CNN-SCR-2026-0988',
      timestamp: '2026-09-30 05:00 PM',
      condition: 'Fresh',
      confidence: 0.97,
      detectedFood: 'Crisp Fresh Vegetables & Leafy Greens',
      visualIndicators: [
        'Vibrant natural turgor pressure in leaves',
        'No wilting, browning, or slime development',
        'Stored in food-safe perforated crates with cold packs',
      ],
      recommendedWindow: 'Safe for 3-4 days under refrigeration',
      advisoryNotes: 'Verified premium produce donation.',
      stage: 'donor',
      inspectorName: 'Chef Rajesh Sharma',
      imageUrl: SAMPLE_FOOD_IMAGES.freshVegetables,
    },
    status: 'COMPLETED',
    createdAt: '2026-09-30 05:15 PM',
    requestedByNGO: {
      ngoId: 'ngo_1',
      ngoName: 'Asha Community Food Bank & Shelter',
      requestedAt: '2026-09-30 05:40 PM',
      beneficiariesTarget: 95,
      notes: 'For community salad bar and dinner stew.',
      ngoLocation: {
        address: 'Mayur Vihar Phase 1, New Delhi',
        lat: 28.6085,
        lng: 77.2965,
      },
    },
    assignedDeliveryPartner: {
      partnerId: 'delivery_1',
      partnerName: 'Amit Verma',
      partnerPhone: '+91 99102 88471',
      vehicleType: 'E-Bike',
      assignedAt: '2026-09-30 06:00 PM',
      pickupTime: '2026-09-30 06:25 PM',
      deliveryTime: '2026-09-30 07:10 PM',
      currentCoordinates: { lat: 28.6085, lng: 77.2965 },
      transitProgress: 100,
      pickupScreening: {
        screeningId: 'CNN-SCR-2026-0994',
        timestamp: '2026-09-30 06:26 PM',
        condition: 'Fresh',
        confidence: 0.96,
        detectedFood: 'Vegetable Crates at Handover',
        visualIndicators: ['Cold storage verified', 'Zero bruising in transit bag'],
        recommendedWindow: 'Direct delivery',
        advisoryNotes: 'Stage 2 pickup check confirmed intact.',
        stage: 'pickup',
        inspectorName: 'Amit Verma',
        imageUrl: SAMPLE_FOOD_IMAGES.freshVegetables,
      },
    },
    receiverVerification: {
      verifiedAt: '2026-09-30 07:15 PM',
      receiverName: 'Sister Mary (Asha Food Bank)',
      verifiedQuantity: 28,
      conditionAccepted: 'Fresh',
      screening: {
        screeningId: 'CNN-SCR-2026-0999',
        timestamp: '2026-09-30 07:18 PM',
        condition: 'Fresh',
        confidence: 0.97,
        detectedFood: 'Received Hydroponic Greens & Peppers',
        visualIndicators: [
          'Full weight verified at receiver scales (28.2 kg)',
          'Crisp and clean leaves without spoilage',
          'Temperature cold check: 5.2°C',
        ],
        recommendedWindow: 'Stored in walk-in cooler',
        advisoryNotes: 'Stage 3 Final Verification completed by receiver. Redistribution successful.',
        stage: 'ngo_final',
        inspectorName: 'Sister Mary (Receiver)',
        imageUrl: SAMPLE_FOOD_IMAGES.freshVegetables,
      },
      remarks: 'Outstanding quality produce! Provided nutritious salads for 95 residents.',
    },
    traceabilityLog: [
      {
        id: 'trc_1',
        timestamp: '2026-09-30 05:15 PM',
        stage: 'Donation Created (Stage 1 AI)',
        status: 'AVAILABLE',
        actor: 'Chef Rajesh Sharma (Donor)',
        actorRole: 'donor',
        note: 'Listed 28 kg produce. AI screened as Fresh (97%).',
      },
      {
        id: 'trc_2',
        timestamp: '2026-09-30 05:40 PM',
        stage: 'NGO Requested',
        status: 'REQUESTED',
        actor: 'Asha Food Bank',
        actorRole: 'ngo',
        note: 'Requested for shelter evening kitchen.',
      },
      {
        id: 'trc_3',
        timestamp: '2026-09-30 05:50 PM',
        stage: 'Donor Approved',
        status: 'APPROVED',
        actor: 'Chef Rajesh Sharma',
        actorRole: 'donor',
        note: 'Approved pickup.',
      },
      {
        id: 'trc_4',
        timestamp: '2026-09-30 06:00 PM',
        stage: 'Delivery Partner Assigned',
        status: 'DELIVERY_PARTNER_ASSIGNED',
        actor: 'Amit Verma',
        actorRole: 'delivery',
        note: 'Accepted task on E-Bike.',
      },
      {
        id: 'trc_5',
        timestamp: '2026-09-30 06:26 PM',
        stage: 'Stage 2 Pickup Verification',
        status: 'COLLECTED',
        actor: 'Amit Verma',
        actorRole: 'delivery',
        note: 'Camera screening verified food condition matches donor record.',
      },
      {
        id: 'trc_6',
        timestamp: '2026-09-30 07:10 PM',
        stage: 'Delivered to NGO Destination',
        status: 'DELIVERED',
        actor: 'Amit Verma',
        actorRole: 'delivery',
        note: 'Safely handed over to Sister Mary.',
      },
      {
        id: 'trc_7',
        timestamp: '2026-09-30 07:18 PM',
        stage: 'Stage 3 Final Receiver Verification',
        status: 'COMPLETED',
        actor: 'Sister Mary (Receiver)',
        actorRole: 'ngo',
        note: 'Physical inspection & final camera scan approved. 28 kg recorded. Chain of custody completed.',
      },
    ],
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif_1',
    title: 'Live Delivery En Route',
    message: 'Delivery partner Amit Verma is currently in transit with 35 kg Vegetable Biryani (SLA-DON-2026-00021). ETA ~18 mins.',
    timestamp: 'Just now',
    type: 'info',
    targetRole: 'all',
    read: false,
    donationId: 'SLA-DON-2026-00021',
  },
  {
    id: 'notif_2',
    title: 'New NGO Request Received',
    message: 'Seva Samarpan Children Foundation requested 50 meals of Dal Khichdi (SLA-DON-2026-00023). Awaiting donor approval.',
    timestamp: '25 mins ago',
    type: 'warning',
    targetRole: 'donor',
    read: false,
    donationId: 'SLA-DON-2026-00023',
  },
  {
    id: 'notif_3',
    title: 'Fresh Surplus Available Nearby',
    message: '45 packs of Artisan Whole Wheat Bread (SLA-DON-2026-00022) available within 3.8 km of your shelter.',
    timestamp: '1 hour ago',
    type: 'success',
    targetRole: 'ngo',
    read: false,
    donationId: 'SLA-DON-2026-00022',
  },
  {
    id: 'notif_4',
    title: 'Donation Completed & Traceability Logged',
    message: 'Hydroponic Produce (SLA-DON-2026-00020) successfully delivered and verified by Asha Food Bank. 28 kg saved.',
    timestamp: 'Yesterday',
    type: 'success',
    targetRole: 'all',
    read: true,
    donationId: 'SLA-DON-2026-00020',
  },
];
